language: cpp
compiler: gcc
dist: xenial
sudo: required
os:
- linux
- osx
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.0-xenial
  ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5 ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install qt512base qt512websockets
  qt512serialport libgl1-mesa-dev ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt512/bin/qt512-env.sh ;
  fi
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/qt/bin:$PATH"
  ; fi
- qmake QUsb2snes.pro
- make
before_deploy:
- macdeployqt QUsb2Snes.app -dmg

deploy:
  provider: releases
  api_key:
    secure: DrWL121m9dQ6lEiwpzKFV1Ha3BvkQ763RRaLN3iWZWnhfqlr+0oei2GObJpzh3jK4nnLdOWGa6iIHPIxGXtfysWEJu4M1joihOOfoTCdjvhTFe0QFl8cQGi/WQkSff8PW6DROE1UrJSKRrgP9InAz4T93IcCP1SNF9Bx4/t3btNY+V8ojTTMzJhj5tyVflInn1h08LzQNxNKLMWJPwca48bwQGKxf6hNJ517OqcmypKMPIIwnPr+FKTL6vICHhIcq47m3jWtzQTh47NoeZfSFNZOZAs+KInRb4MViInUqlobKaJ6Eosz8c+bk9b2bilbwaqOHniHcfNqtruixSrcTuVCBlbP38wLZksnve9k3o7zoJaGpmdItG1jcVJ8oVRF13eTTLPCQ0SMbsRYpL3sHyNOrIHzmFnWB26YbVEhkQ2veYNH1uJQrY6Y8s7G85RpzzgPgbEx9ZGoGl+/nc4OTczIc4ZcAbs/vZtBZrabYSwbeBIAfdiABFBOCXjH1QXkQILvRIQn7zKKhta9KW7hY78aMgfJ4vGcHLPUjKubQ4CcWLh/IevWChV6/GH76lwWIOxXUj7SdeLvoAsQZBqw/MdLjrBN1boB6cpRYV2KmMAUlC4dnKinGyrI0uU7HuP9vQ9p5S6KJRoelbCgI5ck9CbAeJ7WGWeiia3km4UFeuI=
  draft: true
  skip_cleanup: true
  on:
    repo: Skarsnik/QUsb2snes
    tags: false
    condition: $TRAVIS_OS_NAME = osx